spring:
  cloud:
    nacos:
      discovery:
        enabled: false
    gateway:
      routes:
        - id: uber-order-service
          predicates:
            - Path=/order-api/**
          uri: http://localhost:8080
          filters:
            - StripPrefix=1
            - PrefixPath=/api/
